on: push
name: Build site
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install parser
        run: curl -L -o snooty-parser.zip https://github.com/mongodb/snooty-parser/releases/download/v0.16.6/snooty-v0.16.6-linux_x86_64.zip && unzip -d /opt/ snooty-parser.zip
      - name: Add env
        run: echo "/opt/snooty" >> $GITHUB_PATH
      - name: Run parser
        run: snooty build . --output=./bundle.zip
      - name: Build HTML
        run: |
          git clone -b v0.16.13 --depth 1 https://github.com/mongodb/snooty.git 
          echo GATSBY_MANIFEST_PATH=$(pwd) >> ./snooty/.env.production
          cd snooty                
          echo "//artifactory.corp.mongodb.com/artifactory/api/npm/:_authToken=${{ secrets.NPM_AUTH}}" >> ~/.npmrc                                                                
          echo "//artifactory.corp.mongodb.com/artifactory/api/npm/:auth=${{ secrets.NPM_AUTH}}" >> ~/.npmrc                                                                
          npm ci --legacy-peer-deps
          npm run build
