on: push
name: Build site
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install parser
        run: curl -L -o snooty-parser.zip https://github.com/mongodb/snooty-parser/releases/download/v0.16.6/snooty-v0.16.6-linux_x86_64.zip && unzip -d /opt/ snooty-parser.zip
      - name: Add env
        run: echo "/opt/snooty" >> $GITHUB_PATH
      - name: Run parser
        run: snooty build . --output=./bundle.zip
      - name: Build HTML
        env:
          NPM_BASE_64_AUTH: ${{secrets.NPM_AUTH}}
          NPM_EMAIL: ${{secrets.NPM_EMAIL}}
        run: |
          git clone -b v0.16.14 --depth 1 https://github.com/mongodb/snooty.git 
          echo GATSBY_MANIFEST_PATH=$(pwd)/bundle.zip >> ./snooty/.env.production
          cd snooty                
          npm ci --legacy-peer-deps
          git clone --depth 1 https://github.com/mongodb/docs-tools.git
          mkdir -p ./static/images
          mv ./docs-tools/themes/mongodb/static ./static/docs-tools
          mv ./docs-tools/themes/guides/static/images/bg-accent.svg ./static/docs-tools/images/bg-accent.svg
          npm run build
