on: push
name: Build site
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install parser
        run: curl -L -o snooty-parser.zip https://github.com/mongodb/snooty-parser/releases/download/v0.16.6/snooty-v0.16.6-linux_x86_64.zip && unzip -d /opt/ snooty-parser.zip
      - name: Add env
        run: echo "/opt/snooty" >> $GITHUB_PATH
      - name: run parser
        run: snooty build . --output=./bundle.zip
